### ISSUE TITLE
SwapType, WormType, etc are not accesible 

### ISSUE THREAD

**Issue by sergioahv1594** [mi-ghanshyam/onboarding_animation#3]
When I try to set the indicator swap type using the SwapType enum it throws error because it is not accesible.

This is the line I am using:

indicatorSwapType: SwapType.normal,

Error: Undefined name 'SwapType'.

**Comment by AnujMI297** [comment]
@sergioahv1594,
You can now have the accessibility of all the indicator properties including  SwapType and WormType in the new release.
